from .Buscar.alunosPorTurmaListaEquipes import alunosPorTurmaListaEquipes
from .Buscar.buscarAlunos import buscarAlunos
from .Buscar.buscarAlunosPorTurma import buscarAlunosPorTurma
from .Buscar.buscarAlunoPorEquipe import getAlunoEquipe
from .Buscar.buscarTipoDaModalidade import buscarTipoModalidade
from .Buscar.buscarClassificacoes import buscarClassificacoes
from .Buscar.buscarEquipes import buscarEquipes
from .Buscar.buscarEquipesPorEsporte import buscarEquipesPorEsporte
from .Buscar.buscarEquipesPorTurma import buscarEquipesPorTurma
from .Buscar.buscarEsportePorId import buscarEsportePorId
from .Buscar.buscarEstatisticas import buscarEstatisticas
from .Buscar.buscarEstatisticasPorId import buscarEstatisticasPorId
from .Buscar.buscarEstatisticasDeModalidade import buscarEstatisticasDeModalidade
from .Buscar.buscarEstatisticasPorModalidade import buscarEstatisticasPorModalidade
from .Buscar.buscarEsportes import buscarEsportes
from .Buscar.buscarJogadoresPorEquipe import buscarJogadoresPorEquipe
from .Buscar.buscarModalidades import buscarModalidades
from .Buscar.buscarEstatisticasPrincipalPorModalidade import buscarEstatisticasPrincipal
from .Buscar.buscarPartidaPorId import buscarPartidaPorId
from .Buscar.buscarPartidas import buscarPartidas
from .Buscar.buscarTurmas import buscarTurmas
from .Buscar.buscarUsuarioPorNome import buscarUsuarioPorNome
from .Buscar.buscarUsuarios import buscarUsuarios
from .Buscar.buscarEventosCalendario import buscarEventosCalendario
from .Buscar.buscarEventosCalendarioFiltros import buscarEventosCalendarioFiltros
from .Buscar.configuracao import buscarConfiguracao, alterarConfiguracao
from .Buscar.buscarMembrosEquipe import buscarMembrosEquipe
from .Buscar.buscarEstatisticasPrincipalPorModalidade import buscarEstatisticasPrincipal
from .Buscar.buscarEstatisticasRegistradas import buscarEstatisticasRegistradas
from .Buscar.telaUsuarios import telaUsuarios
from .Buscar.buscarEquipesPorId import buscarEquipesPorID
from .Buscar.buscarEstatisticasDasModalidades import buscarEstatisticasDasModalidades
from .Buscar.buscarEsportePorPartida import buscarEsportePorPartida
from .Buscar.buscarEstatisticasDasPartidas import buscarEstatisticasDasPartidas
from .Buscar.buscarProvas import buscarProvas
from .Buscar.buscarProvaPorID import buscarProvaPorID
from .Buscar.buscarPartidasDoDia import buscarPartidasDoDia
from .Buscar.buscarProvasProximas import buscarProvasProximas
from .Cadastrar.cadastrarAluno import cadastrarAluno
from .Cadastrar.cadastrarEquipe import cadastrarEquipe
from .Cadastrar.cadastrarEsportes import cadastrarEsportes
from .Cadastrar.cadastrarEstatisticasParaModalidade import cadastrarEstatisticasParaModalidade
from .Cadastrar.cadastrarTurma import cadastrarTurma
from .Cadastrar.cadastrarUsuario import cadastrarUsuario
from .Cadastrar.criarConexao import criarConexao
from .Cadastrar.criarEstatisticas import criarEstatisticas
from .Cadastrar.criarPartidas import criarPartidas
from .Cadastrar.cadastrarProvaAtletismo import cadastrarProvaAtletismo
from .Cadastrar.cadastrarModalidadeAtletismo import cadastrarModalidadeAtletismo
from .Cadastrar.cadastrarAtletaAtletismo import cadastrarAtletaAtletismo
from .Chaveamento.salvarOuAtualizarEstatisticas import salvarOuAtualizarEstatistica
from .Chaveamento.buscarEquipesPorModCla import buscarEquipesPorModCla
from .Chaveamento.buscarPartidasParaGestao import buscarPartidasParaGestao
from .Chaveamento.gerarProximaRodada import gerarProximaRodada
from .Chaveamento.gestao_chaveamento import gerar_chaveamento_sem_bye_contra_bye
from .Chaveamento.getVencedoresEtapa import getVencedoresEtapa
from .Chaveamento.salvarVencedorPartida import salvarVencedorPartida
from .Chaveamento.verificarEtapaCompleta import verificarEtapaCompleta
from .Deletar.deletarAluno import deletarAluno
from .Deletar.deletarEquipe import deletarEquipe
from .Deletar.deletarTurma import deletarTurma
from .Deletar.deletarUsuario import deletarUsuario
from .Deletar.removerEstatisticas import removerEstatisticas
from .Deletar.removerEstatisticasDaModalidade import removerEstatisticasDaModalidade
from .Deletar.removerModalidade import removerModalidade
from .Deletar.deletarProvaAtletismo import deletarProvaAtletismo
from .Deletar.deletarModalidadeAtletismo import deletarModalidadeAtletismo
from .Editar.editarAluno import editarAluno
from .Editar.editarEquipe import editarEquipe, edicaoEquipesPermitida
from .Editar.editarTurma import editarTurma
from .Editar.editarUsuario import editarUsuario
from .Editar.trocarSenha import trocarSenha
from .Editar.editarModalidadesAtletismo import editarModalidadeAtletismo
